
let screen = new URLSearchParams(location.search).get("phase") ? "chart" : "login";
let currentPhase = new URLSearchParams(location.search).get("phase") || "1";
let activeTab = "summary";
let facultyOpen = false;
function $(id){return document.getElementById(id)}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function phase(){return CASE.phases.find(p=>p.id===currentPhase)||CASE.phases[0]}
function routeToChart(id="1"){screen="chart";currentPhase=id;activeTab="summary";history.replaceState(null,"",`?phase=${id}`);render()}
function setPhase(id){currentPhase=id;activeTab="summary";history.replaceState(null,"",`?phase=${id}`);render()}
function setTab(tab){activeTab=tab;render()}
function toggleFaculty(){facultyOpen=!facultyOpen;const panel=$("facultyPanel");if(panel)panel.classList.toggle("open",facultyOpen)}
function reveal4B(){const val=$("revealCode").value.trim().toUpperCase();if(val==="IPASS")setPhase("4b");else $("revealMsg").textContent="Incorrect code."}
function render(){ $("app").innerHTML = screen==="login" ? renderLogin() : renderChart(); const panel=$("facultyPanel"); if(panel && facultyOpen) panel.classList.add("open");}
function renderLogin(){return `<main class="login"><section class="login-card"><div class="login-hero"><div class="brand-login"><div class="logo">M</div><div><h1>Meridian EMR</h1><div>${esc(CASE.hospital)}</div></div></div><div class="tagline">${esc(CASE.tagline)}</div><p>A fictional pediatric electronic medical record for patient safety simulation.</p></div><div class="login-body"><h2>Hospital Medicine Patient List</h2><p class="muted">Select the active simulation patient. Other patients are placeholders for future cases.</p><div class="patient-list"><div class="patient-tile" onclick="routeToChart('1')"><div><strong>${esc(CASE.patient.name)}</strong><div class="muted">ED → Hospital Medicine · New admission</div></div><span class="pill yellow">Watcher</span></div>${CASE.inactivePatients.map(p=>`<div class="patient-tile disabled"><div><strong>${esc(p.name)}</strong><div class="muted">${esc(p.detail)}</div></div><span class="pill">Future case</span></div>`).join("")}</div></div></section></main>`}
function renderChart(){const p=phase();return `<div class="app"><header class="topbar"><div class="brand" onclick="screen='login';history.replaceState(null,'','./');render()"><div class="brand-mark">M</div><div class="brand-title">Meridian EMR<small>${esc(CASE.hospital)}</small></div></div><div class="top-right"><div class="phase-buttons">${CASE.phases.map(x=>`<button class="${x.id===p.id?'active':''}" onclick="setPhase('${x.id}')">${esc(x.label)}</button>`).join("")}</div><button class="faculty-btn" onclick="toggleFaculty()">Faculty</button></div></header>${renderTabs(p)}${renderStory(p)}<div class="layout"><main><div class="main-title"><div><h2>${esc(p.title)}</h2><p>${esc(p.time)} · ${esc(p.location)}</p></div><span class="pill ${p.status==='worse'?'red':p.status==='same'?'yellow':'green'}">${esc(p.severity)}</span></div><div class="prompt">${esc(p.learnerPrompt)}</div><div class="card"><div class="card-head"><h3>${tabLabel(activeTab)}</h3></div><div class="card-body">${renderTab(p,activeTab)}</div></div></main><aside><div class="card"><div class="card-head"><h3>Messages</h3><span class="count">${p.messages.length}</span></div><div class="card-body">${renderMessages(p)}</div></div><div class="card"><div class="card-head"><h3>Timeline</h3></div><div class="card-body">${renderTimeline(p)}</div></div></aside></div>${renderFaculty(p)}<footer class="footer">Meridian EMR v2.1 · Educational Use Only</footer></div>`}
function renderTabs(p){return `<nav class="folder-tabs">${["summary","notes","orders","mar","results","imaging","flowsheet","growth","messages"].map(t=>`<button class="${activeTab===t?'active':''}" onclick="setTab('${t}')">${tabLabel(t)}${tabCount(p,t)}</button>`).join("")}</nav>`}
function renderStory(p){return `<section class="story"><div class="patient-block">${patientPhoto(p.photoState)}<div class="patient-name"><h2>${esc(CASE.patient.name)}</h2><div>MRN ${esc(CASE.patient.mrn)}</div><div>${esc(CASE.patient.age)} · ${esc(CASE.patient.sex)}</div><div>DOB ${esc(CASE.patient.dob)}</div><div>Room ${esc(p.room || CASE.patient.room || "")}</div><div style="margin-top:8px"><span class="pill ${p.status==='worse'?'red':p.status==='same'?'yellow':'green'}">${esc(p.severity)}</span></div></div></div><div class="story-grid">${story("Hosp Day",p.hospitalDay)}${story("Weight",p.weight)}${story("Allergies",CASE.patient.allergy)}${story("Isolation",CASE.patient.isolation)}${story("Code",CASE.patient.code)}${story("Team",p.team)}${story("PCP",CASE.patient.pcp)}</div></section>`}
function patientPhoto(state){const pale=state==="pale"||state==="critical", critical=state==="critical", sleepy=state==="sleepy"||state==="pale"||state==="critical";const skin=pale?"#e8c7b7":"#f0c49f";const shirt=critical?"#dbeafe":"#2f80b9";const mouth=sleepy?"M52 69c6 2 12 2 18 0":"M52 69c6 5 13 5 19 0";const eyes=sleepy?`<path d="M45 55h9M68 55h9" stroke="#162033" stroke-width="3" stroke-linecap="round"/>`:`<circle cx="49" cy="54" r="4" fill="#162033"/><circle cx="72" cy="54" r="4" fill="#162033"/>`;return `<div class="photo"><svg viewBox="0 0 120 120"><defs><linearGradient id="g${state}" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#dff3f7"/><stop offset="1" stop-color="#f7efe5"/></linearGradient></defs><rect width="120" height="120" fill="url(#g${state})"/><circle cx="60" cy="50" r="30" fill="${skin}"/><path d="M30 48c4-27 53-36 65-6 1 3 0 9-1 12-12-17-43-15-63-6z" fill="#7a4a24"/>${eyes}<path d="${mouth}" fill="none" stroke="#8c3f2b" stroke-width="3" stroke-linecap="round"/><path d="M20 120c6-27 25-39 40-39s34 12 40 39z" fill="${shirt}"/>${critical?`<path d="M40 76c12 7 28 7 40 0" stroke="#6b7280" stroke-width="2"/><path d="M45 47c12-9 24-9 36 0" stroke="#94a3b8" stroke-width="3" fill="none"/>`:``}<path d="M37 37c8-20 43-21 52 0-16-8-35-9-52 0z" fill="#5f371d"/></svg></div>`}
function story(k,v){return `<div class="story-item"><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`}
function tabLabel(t){return ({summary:"Summary",notes:"Notes",orders:"Orders",mar:"MAR",results:"Results Review",imaging:"Imaging",flowsheet:"Flowsheets",growth:"Growth",messages:"Messages"}[t]||t)}
function tabCount(p,t){const map={notes:p.notes,orders:p.orders,mar:p.mar,imaging:p.imaging,growth:p.growth,messages:p.messages};return map[t]?` <span class="count">${map[t].length}</span>`:""}
function renderMessages(p){return p.messages.map(m=>`<div class="msg"><span class="time">${esc(m[1])}</span><div class="from">${esc(m[0])}</div><div>${esc(m[2])}</div></div>`).join("")||"<p>No messages.</p>"}
function renderTimeline(p){return p.timeline.map(x=>`<div class="timeline-item"><time>${esc(x[0])}</time><div>${esc(x[1])}</div></div>`).join("")}
function renderTab(p,t){if(t==="summary")return renderSummary(p);if(t==="notes")return p.notes.map((n,i)=>`<article class="note"><div class="note-head" onclick="$('note${i}').classList.toggle('hidden')"><strong>▾ ${esc(n[0])}</strong><span>${esc(n[1])}</span></div><div class="note-text" id="note${i}">${esc(n[2])}</div></article>`).join("");if(t==="flowsheet")return renderFlowsheet(p,true);if(t==="messages")return renderMessages(p);if(t==="orders")return table(["Order","Details","Status","Comment"],p.orders);if(t==="mar")return table(["Time","Medication","Dose","Status","Comment"],p.mar);if(t==="results")return renderResults(p);if(t==="imaging")return p.imaging.map(i=>`<article class="note"><div class="note-head"><strong>${esc(i[0])}</strong></div><div class="note-text">${esc(i[1])}</div></article>`).join("");if(t==="growth")return table(["Date / age","Weight"],p.growth)+`<p class="muted">Growth history supports weight verification and medication safety review.</p>`}
function renderSummary(p){return `<div class="summary-grid"><div class="mini"><h4>Assessment</h4><ul>${p.summary.assessment.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div><div class="mini"><h4>Overnight / recent events</h4><ul>${p.summary.overnight.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div><div class="mini"><h4>Today's plan</h4><ul>${p.summary.plan.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div><div class="mini"><h4>Pending / To Do</h4><ul>${p.summary.pending.concat(p.summary.tasks).map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div></div><div class="card" style="margin-top:14px"><div class="card-head"><h3>Flowsheet snapshot</h3></div><div class="card-body">${renderFlowsheet(p,false)}</div></div><div class="card"><div class="card-head"><h3>Recent notes</h3></div><div class="card-body">${p.notes.slice(0,4).map(n=>`<article class="note"><div class="note-head"><strong>${esc(n[0])}</strong><span>${esc(n[1])}</span></div></article>`).join("")}</div></div>`}
function renderResults(p){return `<div class="results-grid">${Object.entries(p.results||{}).map(([group,rows])=>`<div class="card"><div class="card-head"><h3>${esc(group)}</h3></div><div class="card-body">${table(["Test","Result","Flag"],rows)}</div></div>`).join("")}</div>`}
function renderFlowsheet(p, includeGraphs){let times=p.flowsheet.times, rows=p.flowsheet.rows;let tableHtml=`<div class="flow-wrap"><table class="flowsheet"><thead><tr><th>Row</th>${times.map(t=>`<th>${esc(t)}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r[0])}</td>${r.slice(1).map(v=>`<td class="${cellClass(r[0],v)}">${esc(v)}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`;return tableHtml+(includeGraphs?`<div class="sparkline-box"><div class="card-head" style="border:1px solid var(--line);border-radius:14px 14px 0 0"><h3>Trend graphs</h3></div><div class="card-body" style="border:1px solid var(--line);border-top:0;border-radius:0 0 14px 14px">${renderTrends(p.flowsheet)}</div></div>`:"")}
function cellClass(row,v){let s=String(v).toLowerCase();let n=parseFloat(v);if(row==="Heart Rate"&&n>=180)return"crit";if(row==="Heart Rate"&&n>=170)return"abn";if(row==="Temperature"&&n>=40)return"crit";if(row==="Temperature"&&n>=39.5)return"abn";if(row==="Respiratory Rate"&&n>=40)return"abn";if(row==="SpO₂"&&n<=92)return"crit";if(s.includes("mottled")||s.includes("difficult")||s.includes("none")||s.includes("weak")||s.includes("5 sec"))return"crit";if(s.includes("low")||s.includes("minimal")||s.includes("cool")||s.includes("4 sec")||s.includes("1+"))return"abn";return""}
function renderTrends(flow){const numericRows=flow.rows.filter(r=>r.slice(1).every(v=>!isNaN(parseFloat(v)))).slice(0,4);return `<div class="trend-grid">${numericRows.map((r,i)=>renderTrend(r[0],r.slice(1).map(Number),i)).join("")}</div>`}
function renderTrend(name,vals,idx){const min=Math.min(...vals),max=Math.max(...vals),w=300,h=125,pad=28;const pts=vals.map((v,i)=>{const x=pad+i*((w-pad*2)/(vals.length-1||1));const y=h-pad-(max===min?.5:(v-min)/(max-min))*(h-pad*2);return [x,y,v]});const path=pts.map((p,i)=>(i?"L":"M")+p[0].toFixed(1)+" "+p[1].toFixed(1)).join(" ");const color=idx<3?"red":"blue";return `<div class="trend"><div class="trend-top"><span>${esc(name)}</span><small>latest ${esc(vals[vals.length-1])}</small></div><svg class="chart" viewBox="0 0 ${w} ${h}"><line class="axis" x1="${pad}" y1="${h-pad}" x2="${w-pad}" y2="${h-pad}"/><line class="axis" x1="${pad}" y1="${pad}" x2="${pad}" y2="${h-pad}"/><path class="line-${color}" d="${path}"/>${pts.map((p,i)=>`<circle class="dot-${color}" cx="${p[0]}" cy="${p[1]}" r="4"/><text class="lab" x="${p[0]}" y="${p[1]-8}" text-anchor="middle">${esc(p[2])}</text><text class="xlab" x="${p[0]}" y="${h-8}" text-anchor="middle">${i+1}</text>`).join("")}</svg></div>`}
function table(head,rows){return `<table class="table"><thead><tr>${head.map(h=>`<th>${esc(h)}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td class="${flagClass(c)}">${esc(c)}</td>`).join("")}</tr>`).join("")}</tbody></table>`}
function flagClass(f){f=String(f).toLowerCase();if(f.includes("critical"))return"flag-critical";if(f.includes("high"))return"flag-high";if(f.includes("low"))return"flag-low";if(f.includes("pending"))return"flag-pending";if(f.includes("prelim"))return"flag-prelim";return""}
function renderFaculty(p){return `<div class="faculty"><button class="faculty-btn" onclick="toggleFaculty()">Faculty</button><div class="faculty-panel ${facultyOpen?'open':''}" id="facultyPanel"><div class="card-head"><h3>Facilitator Mode</h3><button class="primary" onclick="toggleFaculty()">Close</button></div><div class="card-body"><p><strong>Current phase:</strong> ${esc(p.label)} — ${esc(p.title)}</p><p><strong>Teaching notes:</strong></p><ul>${p.facilitator.map(x=>`<li>${esc(x)}</li>`).join("")}</ul>${p.reveal?`<div class="reveal"><strong>Reveal Phase 4B</strong><p>Use after the documentation/handoff debrief.</p><input id="revealCode" placeholder="Code"> <button class="primary" onclick="reveal4B()">Reveal</button><p id="revealMsg"></p></div>`:""}</div></div></div>`}
render();
