
let screen = new URLSearchParams(location.search).get("phase") ? "chart" : "login";
let currentPhase = new URLSearchParams(location.search).get("phase") || "1";
let activeTab = "summary";
let facultyOpen = false;
function $(id){return document.getElementById(id)}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function phase(){return CASE.phases.find(p=>p.id===currentPhase)||CASE.phases[0]}
function routeToChart(id="1"){screen="chart";currentPhase=id;activeTab="summary";history.replaceState(null,"",`?phase=${id}`);render()}
function setPhase(id){currentPhase=id;activeTab="summary";history.replaceState(null,"",`?phase=${id}`);render()}
function setTab(tab){activeTab=tab;render()}
function toggleFaculty(){facultyOpen=!facultyOpen;renderFacultyOnly()}
function renderFacultyOnly(){const panel=$("facultyPanel");if(panel)panel.classList.toggle("open",facultyOpen)}
function reveal4B(){const val=$("revealCode").value.trim().toUpperCase();if(val==="IPASS")setPhase("4b");else $("revealMsg").textContent="Incorrect code."}
function render(){const app=$("app");app.innerHTML=screen==="login"?renderLogin():renderChart();renderFacultyOnly()}

function renderLogin(){return `<main class="login"><section class="login-card"><div class="login-hero"><div class="logo-row"><div class="logo-mark">M</div><div class="logo-text"><h1>Meridian EMR</h1><p>${esc(CASE.hospital)}</p></div></div><div class="tagline">${esc(CASE.tagline)}</div><p>A fictional pediatric electronic medical record for patient safety simulation.</p></div><div class="login-body"><h2>Hospital Medicine Patient List</h2><p class="meta">Select the active simulation patient. Other patients are placeholders for future cases.</p><div class="patient-list"><div class="patient-tile" onclick="routeToChart('1')"><div class="patient-main"><strong>${esc(CASE.patient.name)}</strong><span class="meta">ED → Hospital Medicine · New admission</span></div><span class="badge yellow">Watcher</span></div>${CASE.inactivePatients.map(p=>`<div class="patient-tile disabled"><div class="patient-main"><strong>${esc(p.name)}</strong><span class="meta">${esc(p.detail)}</span></div><span class="badge">Future case</span></div>`).join("")}</div></div></section></main>`}

function renderChart(){
  const p=phase();
  return `<div class="app-shell">
    <header class="topbar"><div class="brand" onclick="screen='login';history.replaceState(null,'','./');render()" title="Return to patient list"><div class="mark">M</div><div>Meridian EMR<small>${esc(CASE.hospital)}</small></div></div><div class="top-actions"><div class="phase-picker">${CASE.phases.map(x=>`<button class="${x.id===p.id?'active':''}" onclick="setPhase('${x.id}')">${esc(x.label)}</button>`).join("")}</div><button class="ghost-btn" onclick="toggleFaculty()">Faculty</button></div></header>
    <nav class="folder-tabs">${["summary","notes","orders","mar","labs","imaging","flowsheet","growth","messages"].map(t=>`<button class="${activeTab===t?'active':''}" onclick="setTab('${t}')">${tabLabel(t)}${tabCount(p,t)}</button>`).join("")}</nav>
    <section class="storyboard">
      <div class="patient-panel">${patientPhoto()}<div class="patient-id"><h2>${esc(CASE.patient.name)}</h2><div class="demographics"><div>MRN ${esc(CASE.patient.mrn)}</div><div>${esc(CASE.patient.age)} · ${esc(CASE.patient.sex)}</div><div>DOB ${esc(CASE.patient.dob)}</div><div>Location ${esc(p.location)}</div><div><span class="badge ${p.status==='worse'?'red':p.status==='same'?'yellow':'green'}">${esc(p.severity)}</span></div></div></div></div>
      <div class="story-grid">${story("Hosp day",p.hospitalDay)}${story("Weight",p.weight)}${story("Allergies",CASE.patient.allergy)}${story("Isolation",CASE.patient.isolation)}${story("Team",p.team)}${story("PCP",CASE.patient.pcp)}</div>
    </section>
    <div class="main-layout">
      <main>
        <div class="phase-title"><div><h2>${esc(p.title)}</h2><p>${esc(p.time)} · ${esc(p.short)}</p></div><span class="badge ${p.status==='worse'?'red':p.status==='same'?'yellow':'green'}">${esc(p.status)}</span></div>
        <div class="learner-prompt">${esc(p.learnerPrompt || "Review the chart and determine what needs attention.")}</div>
        ${p.alerts.map(a=>`<div class="alert ${p.id==='5'?'red':''}">${esc(a)}</div>`).join("")}
        <div class="card"><div class="card-title"><h3>${tabLabel(activeTab)}</h3></div><div class="card-body">${renderTab(p,activeTab)}</div></div>
      </main>
      <aside>
        <div class="card"><div class="card-title"><h3>Messages</h3><span class="count">${p.messages.length}</span></div><div class="card-body">${renderMessages(p)}</div></div>
        <div class="card"><div class="card-title"><h3>Timeline</h3></div><div class="card-body">${renderTimeline(p)}</div></div>
      </aside>
    </div>
    ${renderFaculty(p)}<footer class="footer">Meridian EMR Simulation Platform · Fictional medical record for pediatric patient safety education</footer>
  </div>`
}
function patientPhoto(){return `<div class="patient-photo" aria-label="Illustrated pediatric patient avatar"><svg viewBox="0 0 120 120" role="img"><defs><linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#dff3f7"/><stop offset="1" stop-color="#f7efe5"/></linearGradient></defs><rect width="120" height="120" fill="url(#bg)"/><circle cx="60" cy="50" r="30" fill="#f2c9a7"/><path d="M30 48c4-27 53-36 65-6 1 3 0 9-1 12-12-17-43-15-63-6z" fill="#7a4a24"/><circle cx="49" cy="54" r="4" fill="#162033"/><circle cx="72" cy="54" r="4" fill="#162033"/><path d="M52 70c6 5 13 5 19 0" fill="none" stroke="#8c3f2b" stroke-width="3" stroke-linecap="round"/><path d="M20 120c6-27 25-39 40-39s34 12 40 39z" fill="#2f80b9"/><path d="M37 37c8-20 43-21 52 0-16-8-35-9-52 0z" fill="#5f371d"/></svg></div>`}
function story(k,v){return `<div class="story-item"><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`}
function tabCount(p,t){const map={notes:p.notes,orders:p.orders,mar:p.mar,labs:p.labs,imaging:p.imaging,growth:p.growth,messages:p.messages};return map[t]?` <span class="count">${map[t].length}</span>`:""}
function tabLabel(t){return ({summary:"Summary",notes:"Notes",flowsheet:"Flowsheets",orders:"Orders",mar:"MAR",labs:"Labs",imaging:"Imaging",growth:"Growth",messages:"Messages"}[t]||t)}
function renderTimeline(p){return p.timeline.map(x=>`<div class="timeline-item"><time>${esc(x[0])}</time><div>${esc(x[1])}</div></div>`).join("")}
function renderMessages(p){return p.messages.map(m=>`<div class="msg"><span class="time">${esc(m[1])}</span><div class="from">${esc(m[0])}</div><div>${esc(m[2])}</div></div>`).join("")||"<p>No new messages.</p>"}
function renderTab(p,t){if(t==="summary")return renderSummary(p);if(t==="notes")return p.notes.map((n,i)=>`<article class="note"><div class="note-head" onclick="document.getElementById('note${i}').classList.toggle('hidden')"><strong>▾ ${esc(n[0])}</strong><span>${esc(n[1])}</span></div><div class="note-text" id="note${i}">${esc(n[2])}</div></article>`).join("");if(t==="flowsheet")return renderFlowsheet(p.flowsheet);if(t==="messages")return renderMessages(p);if(t==="orders")return table(["Order","Details","Status","Comment"],p.orders);if(t==="mar")return table(["Time","Medication","Dose","Status","Comment"],p.mar);if(t==="labs")return `<table class="table"><thead><tr><th>Test</th><th>Result</th><th>Flag</th></tr></thead><tbody>${p.labs.map(r=>`<tr><td>${esc(r[0])}</td><td>${esc(r[1])}</td><td class="${flagClass(r[2])}">${esc(r[2])}</td></tr>`).join("")}</tbody></table>`;if(t==="imaging")return p.imaging.map(i=>`<article class="note"><div class="note-head"><strong>${esc(i[0])}</strong></div><div class="note-text">${esc(i[1])}</div></article>`).join("");if(t==="growth")return table(["Date / age","Weight"],p.growth)+`<p class="meta">Growth history supports weight verification and medication safety review.</p>`}
function renderSummary(p){return `<div class="summary-grid"><div class="mini-card"><h4>Current problems</h4><ul>${p.summary.problems.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div><div class="mini-card"><h4>Recent events</h4><ul>${p.summary.recent.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div><div class="mini-card"><h4>Current medications</h4><ul>${(p.currentMeds||[]).map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div><div class="mini-card" style="grid-column:1/-1"><h4>Outstanding tasks</h4><ul>${p.summary.tasks.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div></div><div class="card" style="margin-top:14px"><div class="card-title"><h3>Vital sign trends</h3></div><div class="card-body">${renderFlowsheet(p.flowsheet)}</div></div><div class="card"><div class="card-title"><h3>Recent notes</h3></div><div class="card-body">${p.notes.slice(0,4).map(n=>`<article class="note"><div class="note-head"><strong>${esc(n[0])}</strong><span>${esc(n[1])}</span></div></article>`).join("")}</div></div>`}
function renderFlowsheet(fs){return `<div class="trend-grid">${Object.entries(fs).map(([name,vals],idx)=>renderTrend(name,vals,idx)).join("")}</div>`}
function renderTrend(name,vals,idx){const nums=vals.map(Number),min=Math.min(...nums),max=Math.max(...nums),w=260,h=120,pad=28;const pts=nums.map((v,i)=>{const x=pad+i*((w-pad*2)/(nums.length-1||1));const y=h-pad-(max===min?.5:(v-min)/(max-min))*(h-pad*2);return [x,y,v]}),path=pts.map((p,i)=>(i?"L":"M")+p[0].toFixed(1)+" "+p[1].toFixed(1)).join(" ");const color=idx<2?"red":"blue";return `<div class="trend-card"><div class="trend-head"><span>${esc(name)}</span><small>latest ${esc(vals[vals.length-1])}</small></div><svg class="svg-chart" viewBox="0 0 ${w} ${h}"><line class="axis" x1="${pad}" y1="${h-pad}" x2="${w-pad}" y2="${h-pad}"/><line class="axis" x1="${pad}" y1="${pad}" x2="${pad}" y2="${h-pad}"/><path class="line-${color}" d="${path}"/>${pts.map((p,i)=>`<circle class="dot-${color}" cx="${p[0]}" cy="${p[1]}" r="4"/><text class="chart-label" x="${p[0]}" y="${p[1]-8}" text-anchor="middle">${esc(p[2])}</text><text class="chart-x" x="${p[0]}" y="${h-8}" text-anchor="middle">${i+1}</text>`).join("")}</svg></div>`}
function table(head,rows){return `<table class="table"><thead><tr>${head.map(h=>`<th>${esc(h)}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join("")}</tr>`).join("")}</tbody></table>`}
function flagClass(f){f=String(f).toLowerCase();if(f.includes("critical"))return"flag-critical";if(f.includes("high"))return"flag-high";if(f.includes("low"))return"flag-low";if(f.includes("pending"))return"flag-pending";if(f.includes("prelim"))return"flag-prelim";return""}
function renderFaculty(p){return `<div class="faculty"><button class="primary-btn" onclick="toggleFaculty()">Faculty</button><div class="faculty-panel ${facultyOpen?'open':''}" id="facultyPanel"><div class="card-title"><h3>Facilitator Mode</h3><button class="primary-btn" onclick="toggleFaculty()">Close</button></div><div class="card-body"><p><strong>Current phase:</strong> ${esc(p.label)} — ${esc(p.title)}</p><p><strong>Teaching notes:</strong></p><ul>${p.facilitator.map(x=>`<li>${esc(x)}</li>`).join("")}</ul>${p.reveal?`<div class="reveal"><strong>Reveal Phase 4B</strong><p>Use after the documentation/handoff debrief.</p><input id="revealCode" placeholder="Code"> <button class="primary-btn" onclick="reveal4B()">Reveal</button><p id="revealMsg"></p></div>`:""}</div></div></div>`}
render();
